name: trial-caddy

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    network_mode: host
    # not necessary if Caddy works under network_mode thus it listens to all capable ports
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "443:443/udp"
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./sites:/srv:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80",
        ]
      interval: 1m
      timeout: 10s
      start_period: 10s
